### ISSUE TITLE
Possible font-weight inconsistency with overridden fonts

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/Palettes-for-Tumblr#223]
### Platform

unknown (likely windows)

### Browser

unknown

### Addon version

2.0.0?

### Details

As noted in [this New XKit discord server message](https://discord.com/channels/104051306309644288/104051306309644288/1303287725528711168), with a user style similar to that just added in #215, it may be possible on some systems for certain elements to have inconsistent font weights that are intended for the `--font-family-modern` font when applying an override.

~~I have not yet investigated whether this is still the case, and I can't personally reproduce it.~~ Reproduced in Firefox 135.0b9 on MacOS 14.7.1.

Users with this problem might prefer the `--font-family-modern` override to be a separate toggle that can be disabled. In an ideal world, though, we just fix it.

I'm not necessarily sure how, though; the fix I made is not really maintainable. For reference:

```css
.Vt7qF .wL4YA.jk3gM .UEULa, .vgRpB, .pdHCI, .Xz965, .pEHwj .yY2Oe .v_iz_, .pEHwj .yY2Oe .aQXxD, .vgL3J, .q9P6T, .gAJ73, .gpV8Q, .h7IR_, .ctBr6, .fBQsy, .h6QpP, .o5TqQ, .gty8w, .sG03a, .SuDWJ, .nhqrO.ldaI8, .I3pYl, .NjLa2, .YVaw6 .uJ0hL, .F0gXR, .ZRkRa, .FaPcn, .uPyPt, .mhABv, .YtLa6 .aPaHS, .YtLa6 .G6FrY, .NM1DN .pfmRm, .FzBTa .GpO9n, .c1xDI, .Rl1K_, .SCBLa, .yjhh2, .vSa8M, .xPEP2, .rB7hU, .RPMuM, .f8LOG, .uaMQw, .Jo8I3, .pYQdH .uHcx_, .Nq9JP, .Z7ew7, .amytk, .dJl65, .YmlZc, .KaTRm, .KPqE4 p.zDaqs, .YMD5o, .cYyad, .TZgeO, .Gt2Q9, .n63mn, .OmZD7,.RSZnt, .j8Eiw, .Hzn1C, .YmIEY, .wjhBM, .tSUo6, .NSF9b .vGsK0 .fhLhp, .zGDfg, .c6rjd .Oxjr8, .gDeru p, .Ks9nn .ZR5vI, .Rf1RJ, .gnxzg, .Q53Gq, .ueVRR, .IMMt_, .j2j0M, .afgMB, .HqY8o, .v38by .gSgTK, .cs2zK, .AKAFO .bOGfF, .AiALR .enHco .fgOG_, .mAUoH .Re2fk .nmfdY, .mAUoH .Re2fk .RRf6I, .HfAqf .YGy_k .vpmnx {
  font-weight: 400;
}
```
